# Generated by Django 5.0.3 on 2024-07-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('AdminMagasin', 'adminMagasin'), ('Accueillants', 'accueillants'), ('Caissiers', 'caissiers'), ('Livraisons', 'livraisons')], max_length=255),
        ),
    ]
