# Generated by Django 5.0.3 on 2024-08-31 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
    ]
