# Generated by Django 5.0.3 on 2025-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='profoma',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='profoma',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
