# Generated by Django 5.0.3 on 2024-07-31 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_piece_numero_piece_panier_commande_panieritem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.panier'),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
