# Generated by Django 5.0.3 on 2024-09-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240831_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
    ]
