# Generated by Django 5.0.3 on 2024-09-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_piece_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
