# Generated by Django 5.0.3 on 2024-07-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_commande_panier_alter_panieritem_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='ticket',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
