# Generated by Django 5.0.3 on 2024-08-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_panier_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='panier_paye',
            field=models.BooleanField(default=False),
        ),
    ]
