# Generated by Django 5.0.3 on 2024-09-07 18:08

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_commande_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='id_numero',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='', unique=True),
        ),
    ]
