# Generated by Django 5.0.3 on 2024-09-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_panier_id_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='id_numero',
        ),
    ]
