# Generated by Django 5.0.3 on 2024-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_panier_date_creation_alter_panier_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_reste',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
