# Generated by Django 5.0.3 on 2024-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_commande_montant_paye_commande_montant_reste'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='livre',
            field=models.BooleanField(default=False),
        ),
    ]
