# Generated by Django 5.0.3 on 2024-08-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_panier_livre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='livre',
        ),
    ]
