# Generated by Django 5.0.3 on 2024-08-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_panier_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='panier_livre',
            field=models.BooleanField(default=False),
        ),
    ]
