# Generated by Django 5.0.3 on 2024-08-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_panier_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
