# Generated by Django 5.0.3 on 2024-08-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_panier_panier_livre'),
        ('stock', '0012_alter_commande_panier_alter_panier_utilisateur_and_more'),
    ]

    operations = [
    ]
