<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-08-25 15:30
=======
# Generated by Django 5.0.3 on 2024-08-25 20:46
>>>>>>> a75edca57c091ff6bf37ea1ed2c247e79d686911

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_merge_20240824_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='remise',
<<<<<<< HEAD
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
=======
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
>>>>>>> a75edca57c091ff6bf37ea1ed2c247e79d686911
        ),
    ]
