# Generated by Django 5.0.3 on 2024-08-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_commande_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total_sans_remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
