# Generated by Django 5.0.3 on 2024-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_commande_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='remise',
        ),
    ]
