# Generated by Django 5.0.3 on 2024-08-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_commande_total_sans_remise'),
        ('stock', '0018_commande_remise'),
    ]

    operations = [
    ]
