# version: '3.9'

# services:
#   app:
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#       - postgres_data:/var/lib/postgresql/data
#     command: >
#       sh -c "python manage.py migrate &&
#              python manage.py runserver 0.0.0.0:8000"
#     working_dir: /app
#     env_file:
#       - .env

#   db:
#     image: postgres:latest
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: magasin_piece
#       POSTGRES_USER: magasin_piece_user
#       POSTGRES_PASSWORD: kEz2jKPbm8U7os7mLwdMtqq7C8igzNQk
#     ports:
#       - "5432:5432"  # Optional: expose PostgreSQL port

# volumes:
#   postgres_data:
